### ISSUE TITLE
npm i koa-redis@2 is missing index.js

### ISSUE THREAD

**Issue by thecaddy** [koajs/koa-redis#14]
I may be going crazy, I've done npm rebuild, rm -rf node_modules and npm i and index.js is still missing from the folder.

<img width="202" alt="screen shot 2016-01-11 at 10 18 10 pm" src="https://cloud.githubusercontent.com/assets/1521981/12256323/4cdd4882-b8b1-11e5-8c32-c55d1900e172.png">

**Comment by dead-horse** [comment]
sorry, koa-redis@2.0.1 fixed this issue.

**Comment by DaAwesomeP** [comment]
@dead-horse would you mind explaining what happened? I can't figure it out.
