### ISSUE TITLE
2.0.0 can't install wihtout python

### ISSUE THREAD

**Issue by whwnow** [koajs/koa-redis#17]
I'm using win 10 and node 5.4.1
the dependency hiredis package, can't install without python

![error log](http://ww3.sinaimg.cn/large/0060lm7Tgw1f03nqiejwjj30rp0hfqb4.jpg)

i have installed python and error log show me to install  .NET Framework 2.0 SDK...

**Comment by dead-horse** [comment]
does koa-redis already installed? because `hiredis` is an `optionalDependencies`

**Comment by DaAwesomeP** [comment]
@whwnow at the very bottom of that image, it looks like it `koa-redis@2` *did* successfully install. As @dead-horse said, `hiredis` is optional and only it failed to install. Everything should function as normal.

**Comment by DaAwesomeP** [comment]
@whwnow I believe that `node-gyp` requires Python and Visual Studio (which would give you that SDK). I installed it so long ago, I haven't had this issue in a while. You'll need to check with the `hiredis` package for exact requirements.

**Comment by whwnow** [comment]
thinks @DaAwesomeP @dead-horse 

I have ran the test. the `koa-redis@2` did successfully install when the error came out

I just ignore the error message?

**Comment by DaAwesomeP** [comment]
Yes! Thank you for opening an issue.
