### ISSUE TITLE
Upgrade redis to v2.5

### ISSUE THREAD

**Issue by ratson** [koajs/koa-redis#21]
Some features are deprecating for v3.

**Comment by dead-horse** [comment]
PR's welcome!

**Comment by DaAwesomeP** [comment]
We'll need to update the tests to explictely provide the `flush` argument to the `end()` function. See the deprecation section here: https://github.com/NodeRedis/node_redis/releases/tag/2.5.0-1.

**Comment by DaAwesomeP** [comment]
I created a new branch to test the update. The tests passed, but there are lots of warnings that need to be resolved: https://travis-ci.org/koajs/koa-redis/jobs/116438808. I can look into them by the end of the week, but a PR is welcome.

**Comment by DaAwesomeP** [comment]
Updated in https://github.com/koajs/koa-redis/commit/16bfa029a695f370adb70c9621b280b5da583a8d.

**Comment by DaAwesomeP** [comment]
Released version 2.1.0 with this improvement.
