### ISSUE TITLE
Memory usage might higher with koa-redis?

### ISSUE THREAD

**Issue by marr** [koajs/koa-redis#25]
Hi, I just deployed koa-redis on heroku and I'm seeing my memory usage almost double. Is that expected?
![screen shot 2016-06-02 at 11 48 30 am](https://cloud.githubusercontent.com/assets/44376/15756962/5ca715f0-28b8-11e6-8c14-b2f83bb0d22a.png)
There are two deploys there, the first one is when I introduced koa-redis. Any tips on how to stay under 512MB usage here? I am on a heroku single dyno and using heroku redis instance via the `url` config.

**Comment by DaAwesomeP** [comment]
That does seem high. What version of koa-redis are you using? How does this compare to the cookie session? I'll test this out as well and see what I get. It hopefully isn't caused by the newer version of the redis package.

**Comment by marr** [comment]
I am on koa-redis@2.1.1

I did do a restart of the server and things seem to have gone back down to
normal. I wonder if it was something to do with existing memory sessions on
the server.

**Comment by marr** [comment]
Turns out I accidentally was using react HMR in prod. This was causing the memory usage increase. Closing this as koa-redis isn't at fault here :)
