### ISSUE TITLE
About koa2

### ISSUE THREAD

**Issue by fwh1990** [koajs/koa-redis#29]
Hi,guys.Do you have any plan to support koa2? I can't use this plugin with koa-generic-session in koa2. The code looks like:

const convert = require('koa-convert');
const session = require('koa-generic-session');
const RedisStore = require('koa-redis');

app.use(convert(session({
  store: new RedisStore(),
})));

How to do now? thanks very much.

**Comment by DaAwesomeP** [comment]
There is a pull open to upgrade to Koa 2, but there are some issues with the pull: https://github.com/koajs/koa-redis/pull/28
