### ISSUE TITLE
Prevent hiredis build after each package add/remove

### ISSUE THREAD

**Issue by avetisk** [koajs/koa-redis#39]
Everytime I add or remove a package (using `yarn`), `hiredis` is rebuild (which takes some undesirable amount of time).

Is there anyway to prevent this?

(BTW, this reminds me of the same issue with `node-rdkafka`: https://github.com/Blizzard/node-rdkafka/issues/152)

**Comment by DaAwesomeP** [comment]
From the issue that you attached, it sounds like yarn is working on a workaround. I can't see any other workarounds.

**Comment by avetisk** [comment]
Sorry, I want clear: is there any workaround like the one in the given issue (using an envvar + local build)?

If not, then you can close this issue.

**Comment by DaAwesomeP** [comment]
@avetisk I do not see any trace of an environment variable in the [hiredis repo](https://github.com/redis/hiredis-node). You could maybe open a pull there to this option.
