### ISSUE TITLE
Default method of serialize and unserialize in readme

### ISSUE THREAD

**Issue by Joseph7451797** [koajs/koa-redis#42]
Recently I am working on a side project and use Koa framework. I use [koa-redis](https://github.com/koajs/koa-redis) to get value saved from another server which use [Node redis](https://github.com/NodeRedis/node_redis). 

Problem encountered is the result from unserialize method in koa-redis because I don't use ```JSON.stringify``` while setting(using Node redis). I know use explicit serialized function is a good habit. 

 I found this result after surveying [source code](https://github.com/koajs/koa-redis/blob/master/index.js#L114). Can it be written in README.md explicitly?

**Comment by DaAwesomeP** [comment]
@Joseph7451797 I'm not sure if I understand what your issue is. koa-redis expects JSON data stored in Redis. This is a requirement of koa-generic-session.

**Comment by Joseph7451797** [comment]
> Usage
koa-redis works with koa-generic-session (a generic session middleware for koa).

@DaAwesomeP I got it after reading README.md again.

Maybe the key point of my issue is that I use koa-redis independently(not with ko-generic-session). I will handle JSON data by myself. Thank for your reply.
