### ISSUE TITLE
Renundant optionalDependency

### ISSUE THREAD

**Issue by atassis** [koajs/koa-redis#44]
The [hiredis](https://github.com/koajs/koa-redis/blob/af55af3ea574e4fdbe5ab086054ee9b0ed9ab509/package.json#L40-L42) optionalDependency in package.json is renundant. 
It is used nowhere in the code, but takes a space in image builds, etc.

**Comment by DaAwesomeP** [comment]
Please see #38.

**Comment by atassis** [comment]
Sorry for duplicates, you have answered too fast=)
Why do we need this package? I understand how optional deps work, still see no reason to leave this.

**Comment by DaAwesomeP** [comment]
> Sorry for duplicates, you have answered too fast=)

Ah! No worries!

> Why do we need this package? I understand how optional deps work, still see no reason to leave this.

koa-redis does not explicitly use this package programmatically. It is really an optional dependency for the `redis` package. It provides the C bindings for Redis which are much faster than the JavaScript implementation.

https://www.npmjs.com/package/hiredis
