### ISSUE TITLE
Appears to fail with password@hostname style URI

### ISSUE THREAD

**Issue by jhsware** [koajs/koa-redis#52]
I have used redis in a k8s cluster. When setting the connection using `redis://password@hostname:port` it fails to connect. When using `redis://hostname:port?password=password` it works. It would be nice to be able to use both, or throw an error.

**Comment by Runrioter** [comment]
Format: `[redis:]//[[user][:password@]][host][:port][/db-number][?db=db-number[&password=bar[&option=value]]]`

**Comment by jhsware** [comment]
My bad! Obviously one needs a leading colon...
