### ISSUE TITLE
Cannot add property auth_pass, object is not extensible

### ISSUE THREAD

**Issue by wzkun** [koajs/koa-redis#53]
I meet this problem:'Error while starting up server TypeError: Cannot add property auth_pass, object is not extensible'.
And I use kod-redis like this:

import redisStore from 'koa-redis';

app.use(session({
    prefix: "prefix",
    ttl: 40000,
    rolling: true,
    store: redisStore({
            "host": "192.168.199.189",
            "port": 6379,
            "db": 2
        })
  }));

**Comment by brendtumi** [comment]
Why this ticket closed without explanation? I am getting similar error
`TypeError: Cannot add property password, object is not extensible at new RedisStore (/app/node_modules/koa-redis/lib/index.js:54:20) at RedisStore`
