### ISSUE TITLE
Docs for setting TTL?

### ISSUE THREAD

**Issue by atomgomba** [koajs/koa-redis#8]
I saw there's a TTL argument for the `set` method, but it's not clear to me how to use it and it's not documented. I'm a noob just creating my first app using node.

**Comment by dead-horse** [comment]
koa-redis must used with koa-generic-session, so you can find TTL option [here](https://github.com/koajs/generic-session)

**Comment by atomgomba** [comment]
thank you for your reply! redis's EXPIRE accepts seconds, but there is a division by 1000 in the code. do I still have to pass seconds to koa-generic-session or millis?
